// Generated by CoffeeScript 1.4.0
(function() {
  var config;

  config = {
    "default": 'a'
  };

  angular.module('myApp.config', []).value('config', config);

  config.some_url = 'http:/foo';

}).call(this);
