// Generated by CoffeeScript 1.4.0
(function() {
  var controller, controllers;

  controllers = angular.module('myApp.controllers', ['myApp.services']);

  controller = controllers.controller;

  controller('MyCtrl1', function() {});

  controller('MyCtrl2', function() {});

}).call(this);
