// Generated by CoffeeScript 1.4.0
(function() {
  var controller, controllers;

  controllers = angular.module('myApp.controllers', ['myApp.services']);

  controller = controllers.controller;

  controller('MyCtrl1', function(forge, config) {
    return forge.logging.log('some_url', config.some_url);
  });

  controller('MyCtrl2', function() {});

}).call(this);
