// Generated by CoffeeScript 1.4.0
(function() {
  var directive, directives;

  directives = angular.module('myApp.directives', []);

  directive = directives.directive;

  directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        return elm.text(version);
      };
    }
  ]);

}).call(this);
