// Generated by CoffeeScript 1.4.0
(function() {
  var service, services, value;

  services = angular.module('myApp.services', []);

  value = services.value;

  service = services.service;

  service('forge', function() {
    if (window.forge) {
      return window.forge;
    }
    return {
      "barcode": {
        scan: function(success) {
          if (success) {
            return success();
          }
        }
      },
      "file": {
        getImage: function(options, succes, error) {
          return success();
        }
      },
      "is": {
        web: function() {
          return true;
        }
      },
      "logging": {
        "log": function() {
          return console.log.apply(console, arguments);
        }
      },
      "tabbar": {
        show: function() {},
        hide: function() {},
        addButton: function() {},
        removeButtons: function() {}
      },
      "request": {
        "get": $.get,
        "ajax": $.ajax
      }
    };
  });

  value('version', '0.1');

}).call(this);
